version: 0.2

phases:
    build:
        commands:
            # Building the react app and deploying to S3 bucket, invalidating the CloudFront
            - npm run build
            - npm run deploy
artifacts:
    files:
        - serverless.yml
    base-directory: 'serverless'
    discard-paths: yes