version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build and Deploy started on `date`
      - npm run build && aws s3 sync build/ s3://joshualopesm.com
      - echo Build has finished