version: 0.2

phases:
    build:
        commands:
            # Building the react app and deploying to S3 bucket, invalidating the CloudFront
            - npm install
            - npm run build
            - npm run deploy